### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by A-jha383** [A-jha383/Company_website_templete#1]

**Comment by kvnal** [comment]
I would like to work on this, Please assign me this task

**Comment by kvnal** [comment]
@A-jha383 preloader added #16 👈. pls review.
Thanks!

**Comment by A-jha383** [comment]
thank u Kvnal

**Comment by kvnal** [comment]
> thank u Kvnal

Your welcome @A-jha383 ! can you pls label this PR as hacktoberfest-accepted. Thanks!
